export {
  SESSION_ENDPOINT,
  REALTIME_MODELS,
  MODE_LABELS,
  DEFAULT_MODE,
  SESSION_CAP_MINUTES,
  INTERVIEWER_VOICE,
  VAD_EAGERNESS,
  NOISE_REDUCTION,
  INTERRUPT_RESPONSE,
  type InterviewMode,
} from "./config";
