import openProblemsRaw from "./problems.open.json";
import { EXAMPLES } from "./examples";

export type Difficulty = "Easy" | "Medium" | "Hard";

export type Example = { input: string; output: string; explanation?: string };

export type Problem = {
  id: string;
  title: string;
  difficulty: Difficulty;
  category: string;
  statement: string;
  constraints: string[];
  targetComplexity: string;
  starterCode: string;
  examples: Example[];
  /** Marks problems pulled from the open dataset rather than the curated set. */
  source?: "curated" | "open";
};

/** Display order for categories in the picker (NeetCode 150 structure). */
export const CATEGORIES = [
  "Arrays & Hashing",
  "Two Pointers",
  "Sliding Window",
  "Stack",
  "Binary Search",
  "Linked List",
  "Trees",
  "Tries",
  "Heap / Priority Queue",
  "Backtracking",
  "Graphs",
  "Advanced Graphs",
  "1-D Dynamic Programming",
  "2-D Dynamic Programming",
  "Greedy",
  "Intervals",
  "Math & Geometry",
  "Bit Manipulation",
] as const;

/**
 * Exact platform-specific numeric bounds are intentionally omitted from the
 * candidate view. These rules keep the interview honest without inviting the
 * model to invent missing constraints.
 */
export const DEFAULT_INTERVIEW_CONSTRAINTS = [
  "Use the function signature and statement as the source of truth for input types and validity.",
  "If an exact size bound affects the approach, state a reasonable assumption and confirm it with the interviewer.",
];

const fn = (sig: string) => `function ${sig} {\n\n}`;

const listNode = `class ListNode {
  val: number;
  next: ListNode | null;
  constructor(val = 0, next: ListNode | null = null) {
    this.val = val;
    this.next = next;
  }
}

`;

const treeNode = `class TreeNode {
  val: number;
  left: TreeNode | null;
  right: TreeNode | null;
  constructor(val = 0, left: TreeNode | null = null, right: TreeNode | null = null) {
    this.val = val;
    this.left = left;
    this.right = right;
  }
}

`;

const p = (
  id: string,
  title: string,
  difficulty: Difficulty,
  category: string,
  statement: string,
  targetComplexity: string,
  starterCode: string,
  constraints: string[] = DEFAULT_INTERVIEW_CONSTRAINTS,
): Problem => ({
  id,
  title,
  difficulty,
  category,
  statement,
  constraints,
  targetComplexity,
  starterCode,
  examples: EXAMPLES[id] ?? [],
});

export const PROBLEMS: Problem[] = [
  // ---------- Arrays & Hashing ----------
  p("contains-duplicate", "Contains Duplicate", "Easy", "Arrays & Hashing",
    "Return true if any value in the array appears at least twice, false if all elements are distinct.",
    "O(n) time, O(n) space", fn("containsDuplicate(nums: number[]): boolean")),
  p("valid-anagram", "Valid Anagram", "Easy", "Arrays & Hashing",
    "Given two strings, return true if one is a rearrangement of the other using the same characters with the same counts.",
    "O(n) time", fn("isAnagram(s: string, t: string): boolean")),
  p("two-sum", "Two Sum", "Easy", "Arrays & Hashing",
    "Return the indices of the two numbers that add up to a target. Exactly one pair works and no element is reused.",
    "O(n) time, O(n) space", fn("twoSum(nums: number[], target: number): number[]")),
  p("group-anagrams", "Group Anagrams", "Medium", "Arrays & Hashing",
    "Group the strings that are anagrams of one another and return the groups in any order.",
    "O(n·k) time", fn("groupAnagrams(strs: string[]): string[][]")),
  p("top-k-frequent", "Top K Frequent Elements", "Medium", "Arrays & Hashing",
    "Return the k most frequently occurring elements, in any order.",
    "O(n) time with bucket sort", fn("topKFrequent(nums: number[], k: number): number[]")),
  p("product-except-self", "Product of Array Except Self", "Medium", "Arrays & Hashing",
    "Return an array where each position holds the product of all other elements, without using division.",
    "O(n) time, O(1) extra", fn("productExceptSelf(nums: number[]): number[]")),
  p("valid-sudoku", "Valid Sudoku", "Medium", "Arrays & Hashing",
    "Given a 9×9 board, decide whether the filled cells violate any row, column, or 3×3 box uniqueness rule.",
    "O(1) (fixed 81 cells)", fn("isValidSudoku(board: string[][]): boolean")),
  p("encode-decode-strings", "Encode and Decode Strings", "Medium", "Arrays & Hashing",
    "Design encode and decode so a list of arbitrary strings can be serialized to a single string and recovered exactly.",
    "O(n) time", `function encode(strs: string[]): string {\n\n}\n\nfunction decode(s: string): string[] {\n\n}`),
  p("longest-consecutive", "Longest Consecutive Sequence", "Medium", "Arrays & Hashing",
    "Return the length of the longest run of consecutive integers present in the array, in O(n) time.",
    "O(n) time", fn("longestConsecutive(nums: number[]): number")),

  // ---------- Two Pointers ----------
  p("valid-palindrome", "Valid Palindrome", "Easy", "Two Pointers",
    "Return true if the string reads the same both ways considering only alphanumeric characters and ignoring case.",
    "O(n) time, O(1) space", fn("isPalindrome(s: string): boolean")),
  p("two-sum-ii", "Two Sum II — Sorted Input", "Medium", "Two Pointers",
    "Given a 1-indexed sorted array, return the 1-based indices of two numbers that sum to a target, using O(1) extra space.",
    "O(n) time, O(1) space", fn("twoSum(numbers: number[], target: number): number[]")),
  p("three-sum", "3Sum", "Medium", "Two Pointers",
    "Return all unique triplets that sum to zero. The result must not contain duplicate triplets.",
    "O(n^2) time", fn("threeSum(nums: number[]): number[][]")),
  p("container-most-water", "Container With Most Water", "Medium", "Two Pointers",
    "Each value is a vertical line height; pick two lines that together with the x-axis hold the most water and return that area.",
    "O(n) time", fn("maxArea(height: number[]): number")),
  p("trapping-rain-water", "Trapping Rain Water", "Hard", "Two Pointers",
    "Given an elevation map of bar heights, compute how many units of water are trapped after rain.",
    "O(n) time, O(1) space", fn("trap(height: number[]): number")),

  // ---------- Sliding Window ----------
  p("best-time-stock", "Best Time to Buy and Sell Stock", "Easy", "Sliding Window",
    "Given daily prices, return the max profit from one buy followed by a later sell, or 0 if none.",
    "O(n) time, O(1) space", fn("maxProfit(prices: number[]): number")),
  p("longest-substring", "Longest Substring Without Repeating Characters", "Medium", "Sliding Window",
    "Return the length of the longest contiguous substring containing no repeated characters.",
    "O(n) time", fn("lengthOfLongestSubstring(s: string): number")),
  p("longest-repeating-replacement", "Longest Repeating Character Replacement", "Medium", "Sliding Window",
    "You may replace up to k characters; return the length of the longest substring of a single repeated character achievable.",
    "O(n) time", fn("characterReplacement(s: string, k: number): number")),
  p("permutation-in-string", "Permutation in String", "Medium", "Sliding Window",
    "Return true if the second string contains any permutation of the first as a contiguous substring.",
    "O(n) time", fn("checkInclusion(s1: string, s2: string): boolean")),
  p("min-window-substring", "Minimum Window Substring", "Hard", "Sliding Window",
    "Return the shortest substring of s that contains every character of t (with multiplicity), or empty string if none.",
    "O(n) time", fn("minWindow(s: string, t: string): string")),
  p("sliding-window-maximum", "Sliding Window Maximum", "Hard", "Sliding Window",
    "For each window of size k sliding across the array, return the maximum of that window.",
    "O(n) time with a deque", fn("maxSlidingWindow(nums: number[], k: number): number[]")),

  // ---------- Stack ----------
  p("valid-parentheses", "Valid Parentheses", "Easy", "Stack",
    "Given a string of just ()[]{}, return true if every bracket closes with the matching type in the correct order.",
    "O(n) time, O(n) space", fn("isValid(s: string): boolean")),
  p("min-stack", "Min Stack", "Medium", "Stack",
    "Design a stack supporting push, pop, top, and retrieving the minimum, each in constant time.",
    "O(1) per operation",
    `class MinStack {\n  constructor() {\n\n  }\n  push(val: number): void {\n\n  }\n  pop(): void {\n\n  }\n  top(): number {\n\n  }\n  getMin(): number {\n\n  }\n}`),
  p("eval-rpn", "Evaluate Reverse Polish Notation", "Medium", "Stack",
    "Evaluate an arithmetic expression given in Reverse Polish (postfix) notation and return the integer result.",
    "O(n) time", fn("evalRPN(tokens: string[]): number")),
  p("generate-parentheses", "Generate Parentheses", "Medium", "Stack",
    "Given n pairs, return every well-formed string of n opening and n closing parentheses.",
    "O(4^n / √n) time", fn("generateParenthesis(n: number): string[]")),
  p("daily-temperatures", "Daily Temperatures", "Medium", "Stack",
    "For each day return how many days you must wait for a warmer temperature, or 0 if none comes.",
    "O(n) time", fn("dailyTemperatures(temperatures: number[]): number[]")),
  p("car-fleet", "Car Fleet", "Medium", "Stack",
    "Cars head to a target at given positions and speeds; cars that catch up form a fleet. Return how many fleets reach the target.",
    "O(n log n) time", fn("carFleet(target: number, position: number[], speed: number[]): number")),
  p("largest-rectangle-histogram", "Largest Rectangle in Histogram", "Hard", "Stack",
    "Given bar heights of width 1, return the area of the largest rectangle that fits within the histogram.",
    "O(n) time", fn("largestRectangleArea(heights: number[]): number")),

  // ---------- Binary Search ----------
  p("binary-search", "Binary Search", "Easy", "Binary Search",
    "Given a sorted array of distinct integers and a target, return its index or -1, in logarithmic time.",
    "O(log n) time", fn("search(nums: number[], target: number): number")),
  p("search-2d-matrix", "Search a 2D Matrix", "Medium", "Binary Search",
    "Each row is sorted and each row's first value exceeds the previous row's last; return whether a target exists.",
    "O(log(m·n)) time", fn("searchMatrix(matrix: number[][], target: number): boolean")),
  p("koko-bananas", "Koko Eating Bananas", "Medium", "Binary Search",
    "Find the smallest integer eating speed that lets Koko finish all banana piles within h hours.",
    "O(n log m) time", fn("minEatingSpeed(piles: number[], h: number): number")),
  p("find-min-rotated", "Find Minimum in Rotated Sorted Array", "Medium", "Binary Search",
    "A sorted array of distinct values was rotated; return its minimum element in logarithmic time.",
    "O(log n) time", fn("findMin(nums: number[]): number")),
  p("search-rotated", "Search in Rotated Sorted Array", "Medium", "Binary Search",
    "A sorted array of distinct values was rotated at an unknown pivot; return a target's index or -1, in log time.",
    "O(log n) time", fn("search(nums: number[], target: number): number")),
  p("time-based-store", "Time Based Key-Value Store", "Medium", "Binary Search",
    "Design a store where set saves a value at a timestamp and get returns the value with the largest timestamp ≤ the query.",
    "O(log n) per get",
    `class TimeMap {\n  constructor() {\n\n  }\n  set(key: string, value: string, timestamp: number): void {\n\n  }\n  get(key: string, timestamp: number): string {\n\n  }\n}`),
  p("median-two-sorted", "Median of Two Sorted Arrays", "Hard", "Binary Search",
    "Given two sorted arrays, return the median of their combined ordering in logarithmic time.",
    "O(log(m+n)) time", fn("findMedianSortedArrays(a: number[], b: number[]): number")),

  // ---------- Linked List ----------
  p("reverse-linked-list", "Reverse Linked List", "Easy", "Linked List",
    "Reverse a singly linked list in place and return the new head; try the iterative approach first.",
    "O(n) time, O(1) space", listNode + fn("reverseList(head: ListNode | null): ListNode | null")),
  p("merge-two-lists", "Merge Two Sorted Lists", "Easy", "Linked List",
    "Splice two sorted linked lists into one sorted list and return its head.",
    "O(n+m) time, O(1) space", listNode + fn("mergeTwoLists(a: ListNode | null, b: ListNode | null): ListNode | null")),
  p("reorder-list", "Reorder List", "Medium", "Linked List",
    "Reorder a list so it alternates first, last, second, second-last, … in place, modifying node links only.",
    "O(n) time, O(1) space", listNode + fn("reorderList(head: ListNode | null): void")),
  p("remove-nth-end", "Remove Nth Node From End of List", "Medium", "Linked List",
    "Remove the n-th node counting from the end and return the head, ideally in one pass.",
    "O(n) time, O(1) space", listNode + fn("removeNthFromEnd(head: ListNode | null, n: number): ListNode | null")),
  p("copy-random-list", "Copy List With Random Pointer", "Medium", "Linked List",
    "Each node has a next and a random pointer; return a deep copy of the whole list.",
    "O(n) time",
    `class RNode {\n  val: number;\n  next: RNode | null = null;\n  random: RNode | null = null;\n  constructor(val = 0) {\n    this.val = val;\n  }\n}\n\n${fn("copyRandomList(head: RNode | null): RNode | null")}`),
  p("add-two-numbers", "Add Two Numbers", "Medium", "Linked List",
    "Two numbers are stored as linked lists in reverse-digit order; return their sum as a list in the same form.",
    "O(n) time", listNode + fn("addTwoNumbers(a: ListNode | null, b: ListNode | null): ListNode | null")),
  p("linked-list-cycle", "Linked List Cycle", "Easy", "Linked List",
    "Return true if the linked list contains a cycle, using constant extra space.",
    "O(n) time, O(1) space", listNode + fn("hasCycle(head: ListNode | null): boolean")),
  p("find-duplicate", "Find the Duplicate Number", "Medium", "Linked List",
    "An array of n+1 integers in range [1,n] has exactly one repeated value; find it without modifying the array, in O(1) space.",
    "O(n) time, O(1) space (Floyd's)", fn("findDuplicate(nums: number[]): number")),
  p("lru-cache", "LRU Cache", "Medium", "Linked List",
    "Design a cache with capacity that supports get and put in O(1), evicting the least-recently-used key when full.",
    "O(1) per operation",
    `class LRUCache {\n  constructor(capacity: number) {\n\n  }\n  get(key: number): number {\n\n  }\n  put(key: number, value: number): void {\n\n  }\n}`),
  p("merge-k-lists", "Merge K Sorted Lists", "Hard", "Linked List",
    "Merge k sorted linked lists into one sorted list and return its head.",
    "O(n log k) time", listNode + fn("mergeKLists(lists: Array<ListNode | null>): ListNode | null")),
  p("reverse-k-group", "Reverse Nodes in k-Group", "Hard", "Linked List",
    "Reverse the list in consecutive groups of k; a trailing group smaller than k stays as-is.",
    "O(n) time, O(1) space", listNode + fn("reverseKGroup(head: ListNode | null, k: number): ListNode | null")),

  // ---------- Trees ----------
  p("invert-tree", "Invert Binary Tree", "Easy", "Trees",
    "Swap every node's left and right child and return the root.",
    "O(n) time", treeNode + fn("invertTree(root: TreeNode | null): TreeNode | null")),
  p("max-depth", "Maximum Depth of Binary Tree", "Easy", "Trees",
    "Return the number of nodes on the longest path from root down to a leaf.",
    "O(n) time", treeNode + fn("maxDepth(root: TreeNode | null): number")),
  p("diameter-tree", "Diameter of Binary Tree", "Easy", "Trees",
    "Return the length (in edges) of the longest path between any two nodes in the tree.",
    "O(n) time", treeNode + fn("diameterOfBinaryTree(root: TreeNode | null): number")),
  p("balanced-tree", "Balanced Binary Tree", "Easy", "Trees",
    "Return true if every node's two subtrees differ in height by at most one.",
    "O(n) time", treeNode + fn("isBalanced(root: TreeNode | null): boolean")),
  p("same-tree", "Same Tree", "Easy", "Trees",
    "Given two binary trees, return true if they have identical structure and node values.",
    "O(n) time", treeNode + fn("isSameTree(a: TreeNode | null, b: TreeNode | null): boolean")),
  p("subtree-of-another", "Subtree of Another Tree", "Easy", "Trees",
    "Return true if the second tree appears as a subtree (matching structure and values) somewhere in the first.",
    "O(n·m) time", treeNode + fn("isSubtree(root: TreeNode | null, subRoot: TreeNode | null): boolean")),
  p("lca-bst", "Lowest Common Ancestor of a BST", "Medium", "Trees",
    "In a binary search tree, return the lowest node that is an ancestor of both given nodes.",
    "O(h) time", treeNode + fn("lowestCommonAncestor(root: TreeNode, p: TreeNode, q: TreeNode): TreeNode")),
  p("level-order", "Binary Tree Level Order Traversal", "Medium", "Trees",
    "Return node values level by level, left to right, as an array of arrays.",
    "O(n) time", treeNode + fn("levelOrder(root: TreeNode | null): number[][]")),
  p("right-side-view", "Binary Tree Right Side View", "Medium", "Trees",
    "Return the values visible when looking at the tree from the right side, top to bottom.",
    "O(n) time", treeNode + fn("rightSideView(root: TreeNode | null): number[]")),
  p("count-good-nodes", "Count Good Nodes in Binary Tree", "Medium", "Trees",
    "Count nodes for which no node on the path from the root has a strictly greater value.",
    "O(n) time", treeNode + fn("goodNodes(root: TreeNode): number")),
  p("validate-bst", "Validate Binary Search Tree", "Medium", "Trees",
    "Return true if the tree is a valid BST: every left subtree is smaller and every right subtree larger, recursively.",
    "O(n) time", treeNode + fn("isValidBST(root: TreeNode | null): boolean")),
  p("kth-smallest-bst", "Kth Smallest Element in a BST", "Medium", "Trees",
    "Return the k-th smallest value in a binary search tree.",
    "O(h + k) time", treeNode + fn("kthSmallest(root: TreeNode | null, k: number): number")),
  p("build-tree-pre-in", "Construct Tree from Preorder and Inorder", "Medium", "Trees",
    "Given preorder and inorder traversals of a tree with unique values, reconstruct and return the tree.",
    "O(n) time", treeNode + fn("buildTree(preorder: number[], inorder: number[]): TreeNode | null")),
  p("max-path-sum", "Binary Tree Maximum Path Sum", "Hard", "Trees",
    "Return the maximum sum of any path (a sequence of connected nodes) in the tree; a path need not pass through the root.",
    "O(n) time", treeNode + fn("maxPathSum(root: TreeNode | null): number")),
  p("serialize-deserialize", "Serialize and Deserialize Binary Tree", "Hard", "Trees",
    "Design serialize and deserialize so any binary tree can be turned into a string and rebuilt exactly.",
    "O(n) time",
    treeNode + `function serialize(root: TreeNode | null): string {\n\n}\n\nfunction deserialize(data: string): TreeNode | null {\n\n}`),

  // ---------- Tries ----------
  p("implement-trie", "Implement Trie (Prefix Tree)", "Medium", "Tries",
    "Implement a trie supporting insert, search (exact word), and startsWith (prefix).",
    "O(L) per operation",
    `class Trie {\n  constructor() {\n\n  }\n  insert(word: string): void {\n\n  }\n  search(word: string): boolean {\n\n  }\n  startsWith(prefix: string): boolean {\n\n  }\n}`),
  p("add-search-words", "Design Add and Search Words", "Medium", "Tries",
    "Support addWord and search, where a search pattern may use '.' to match any single character.",
    "O(L) add, O(26^L) worst search",
    `class WordDictionary {\n  constructor() {\n\n  }\n  addWord(word: string): void {\n\n  }\n  search(word: string): boolean {\n\n  }\n}`),
  p("word-search-ii", "Word Search II", "Hard", "Tries",
    "Given a board of letters and a word list, return all listed words that can be formed along adjacent-cell paths without reusing a cell.",
    "O(cells·4^L) with a trie", fn("findWords(board: string[][], words: string[]): string[]")),

  // ---------- Heap / Priority Queue ----------
  p("kth-largest-stream", "Kth Largest Element in a Stream", "Easy", "Heap / Priority Queue",
    "Design a class that returns the k-th largest value seen so far each time a new value is added.",
    "O(log k) per add",
    `class KthLargest {\n  constructor(k: number, nums: number[]) {\n\n  }\n  add(val: number): number {\n\n  }\n}`),
  p("last-stone-weight", "Last Stone Weight", "Easy", "Heap / Priority Queue",
    "Repeatedly smash the two heaviest stones (the difference returns to the pile); return the last stone's weight or 0.",
    "O(n log n) time", fn("lastStoneWeight(stones: number[]): number")),
  p("k-closest-points", "K Closest Points to Origin", "Medium", "Heap / Priority Queue",
    "Return the k points nearest the origin by Euclidean distance, in any order.",
    "O(n log k) time", fn("kClosest(points: number[][], k: number): number[][]")),
  p("kth-largest-array", "Kth Largest Element in an Array", "Medium", "Heap / Priority Queue",
    "Return the k-th largest element in the array (k-th in sorted order, not distinct).",
    "O(n) average (quickselect)", fn("findKthLargest(nums: number[], k: number): number")),
  p("task-scheduler", "Task Scheduler", "Medium", "Heap / Priority Queue",
    "Given tasks and a cooldown n between identical tasks, return the least number of time units to finish all of them.",
    "O(n) time", fn("leastInterval(tasks: string[], n: number): number")),
  p("design-twitter", "Design Twitter", "Medium", "Heap / Priority Queue",
    "Design Twitter with postTweet, getNewsFeed (10 most recent from self + followees), follow, and unfollow.",
    "O(n log n) per feed",
    `class Twitter {\n  constructor() {\n\n  }\n  postTweet(userId: number, tweetId: number): void {\n\n  }\n  getNewsFeed(userId: number): number[] {\n\n  }\n  follow(followerId: number, followeeId: number): void {\n\n  }\n  unfollow(followerId: number, followeeId: number): void {\n\n  }\n}`),
  p("median-data-stream", "Find Median from Data Stream", "Hard", "Heap / Priority Queue",
    "Design addNum and findMedian so the running median of all numbers added so far is available efficiently.",
    "O(log n) add, O(1) median",
    `class MedianFinder {\n  constructor() {\n\n  }\n  addNum(num: number): void {\n\n  }\n  findMedian(): number {\n\n  }\n}`),

  // ---------- Backtracking ----------
  p("subsets", "Subsets", "Medium", "Backtracking",
    "Given distinct integers, return all possible subsets (the power set) with no duplicates.",
    "O(n·2^n) time", fn("subsets(nums: number[]): number[][]")),
  p("combination-sum", "Combination Sum", "Medium", "Backtracking",
    "Return all unique combinations of distinct candidates that sum to a target; each candidate may be reused unlimited times.",
    "exponential", fn("combinationSum(candidates: number[], target: number): number[][]")),
  p("permutations", "Permutations", "Medium", "Backtracking",
    "Return all possible orderings of an array of distinct integers.",
    "O(n·n!) time", fn("permute(nums: number[]): number[][]")),
  p("subsets-ii", "Subsets II", "Medium", "Backtracking",
    "Given integers that may contain duplicates, return all unique subsets.",
    "O(n·2^n) time", fn("subsetsWithDup(nums: number[]): number[][]")),
  p("combination-sum-ii", "Combination Sum II", "Medium", "Backtracking",
    "Return all unique combinations summing to a target where each candidate may be used at most once (input may have duplicates).",
    "exponential", fn("combinationSum2(candidates: number[], target: number): number[][]")),
  p("word-search", "Word Search", "Medium", "Backtracking",
    "Return true if a word can be traced through adjacent cells of a letter grid without reusing any cell.",
    "O(cells·4^L) time", fn("exist(board: string[][], word: string): boolean")),
  p("palindrome-partitioning", "Palindrome Partitioning", "Medium", "Backtracking",
    "Return every way to split the string so that each resulting piece is a palindrome.",
    "O(n·2^n) time", fn("partition(s: string): string[][]")),
  p("letter-combinations", "Letter Combinations of a Phone Number", "Medium", "Backtracking",
    "Given digits 2–9, return all letter strings they could spell using the classic phone keypad mapping.",
    "O(4^n) time", fn("letterCombinations(digits: string): string[]")),
  p("n-queens", "N-Queens", "Hard", "Backtracking",
    "Place n queens on an n×n board so none attack another; return all distinct board configurations.",
    "O(n!) time", fn("solveNQueens(n: number): string[][]")),

  // ---------- Graphs ----------
  p("number-of-islands", "Number of Islands", "Medium", "Graphs",
    "Count islands in a grid of '1' (land) and '0' (water), where land connects horizontally or vertically.",
    "O(rows·cols) time", fn("numIslands(grid: string[][]): number")),
  p("max-area-island", "Max Area of Island", "Medium", "Graphs",
    "Return the area of the largest island (count of connected land cells) in a binary grid, or 0 if none.",
    "O(rows·cols) time", fn("maxAreaOfIsland(grid: number[][]): number")),
  p("clone-graph", "Clone Graph", "Medium", "Graphs",
    "Given a node of a connected undirected graph, return a deep copy of the whole graph.",
    "O(V+E) time",
    `class GraphNode {\n  val: number;\n  neighbors: GraphNode[];\n  constructor(val = 0, neighbors: GraphNode[] = []) {\n    this.val = val;\n    this.neighbors = neighbors;\n  }\n}\n\n${fn("cloneGraph(node: GraphNode | null): GraphNode | null")}`),
  p("walls-and-gates", "Walls and Gates", "Medium", "Graphs",
    "Fill each empty room in a grid with its distance to the nearest gate; rooms that can't reach a gate stay as infinity.",
    "O(rows·cols) time", fn("wallsAndGates(rooms: number[][]): void")),
  p("rotting-oranges", "Rotting Oranges", "Medium", "Graphs",
    "Each minute, rotten oranges rot adjacent fresh ones; return the minutes until none are fresh, or -1 if impossible.",
    "O(rows·cols) time", fn("orangesRotting(grid: number[][]): number")),
  p("pacific-atlantic", "Pacific Atlantic Water Flow", "Medium", "Graphs",
    "Given a height grid, return all cells from which water can flow to both the Pacific (top/left) and Atlantic (bottom/right) edges.",
    "O(rows·cols) time", fn("pacificAtlantic(heights: number[][]): number[][]")),
  p("surrounded-regions", "Surrounded Regions", "Medium", "Graphs",
    "Capture every region of 'O's fully surrounded by 'X'; regions touching a border are not captured.",
    "O(rows·cols) time", fn("solve(board: string[][]): void")),
  p("course-schedule", "Course Schedule", "Medium", "Graphs",
    "Given prerequisite pairs [a,b] meaning b before a, return whether all courses can be finished (no cycle).",
    "O(V+E) time", fn("canFinish(numCourses: number, prerequisites: number[][]): boolean")),
  p("course-schedule-ii", "Course Schedule II", "Medium", "Graphs",
    "Return any valid order to take all courses given prerequisites, or an empty array if impossible.",
    "O(V+E) time", fn("findOrder(numCourses: number, prerequisites: number[][]): number[]")),
  p("graph-valid-tree", "Graph Valid Tree", "Medium", "Graphs",
    "Given n nodes and an edge list, return true if the graph forms a valid tree (connected and acyclic).",
    "O(V+E) time", fn("validTree(n: number, edges: number[][]): boolean")),
  p("connected-components", "Number of Connected Components", "Medium", "Graphs",
    "Given n nodes and an undirected edge list, return how many connected components the graph has.",
    "O(V+E) time", fn("countComponents(n: number, edges: number[][]): number")),
  p("redundant-connection", "Redundant Connection", "Medium", "Graphs",
    "A tree had one extra edge added to form a cycle; return the edge that can be removed, preferring the last one listed.",
    "O(n) time (union-find)", fn("findRedundantConnection(edges: number[][]): number[]")),
  p("word-ladder", "Word Ladder", "Hard", "Graphs",
    "Return the length of the shortest transformation from begin to end word, changing one letter at a time through the word list, or 0.",
    "O(n·L^2) time", fn("ladderLength(beginWord: string, endWord: string, wordList: string[]): number")),

  // ---------- Advanced Graphs ----------
  p("reconstruct-itinerary", "Reconstruct Itinerary", "Hard", "Advanced Graphs",
    "Given airline tickets [from,to], reconstruct the itinerary starting at 'JFK' that uses all tickets, choosing the lexicographically smallest.",
    "O(E log E) time", fn("findItinerary(tickets: string[][]): string[]")),
  p("min-cost-connect-points", "Min Cost to Connect All Points", "Medium", "Advanced Graphs",
    "Given 2D points, connect all of them with minimum total Manhattan-distance cost (a minimum spanning tree).",
    "O(n^2) time (Prim's)", fn("minCostConnectPoints(points: number[][]): number")),
  p("network-delay-time", "Network Delay Time", "Medium", "Advanced Graphs",
    "Given directed weighted edges (u,v,w), return the time for a signal from node k to reach every node, or -1 if some can't.",
    "O(E log V) time (Dijkstra)", fn("networkDelayTime(times: number[][], n: number, k: number): number")),
  p("swim-in-water", "Swim in Rising Water", "Hard", "Advanced Graphs",
    "Water level rises each step; return the least time at which you can travel from the top-left to bottom-right of an elevation grid.",
    "O(n^2 log n) time", fn("swimInWater(grid: number[][]): number")),
  p("alien-dictionary", "Alien Dictionary", "Hard", "Advanced Graphs",
    "Given words sorted by an unknown alphabet, return a possible ordering of its characters, or empty string if invalid.",
    "O(total chars) time", fn("alienOrder(words: string[]): string")),
  p("cheapest-flights-k-stops", "Cheapest Flights Within K Stops", "Medium", "Advanced Graphs",
    "Given flights (from,to,price), return the cheapest cost from src to dst using at most k stops, or -1.",
    "O(k·E) time (Bellman-Ford)", fn("findCheapestPrice(n: number, flights: number[][], src: number, dst: number, k: number): number")),

  // ---------- 1-D Dynamic Programming ----------
  p("climbing-stairs", "Climbing Stairs", "Easy", "1-D Dynamic Programming",
    "You climb 1 or 2 steps at a time; return the number of distinct ways to reach the top of n steps.",
    "O(n) time, O(1) space", fn("climbStairs(n: number): number")),
  p("min-cost-climbing-stairs", "Min Cost Climbing Stairs", "Easy", "1-D Dynamic Programming",
    "Each step has a cost; you may start at step 0 or 1 and climb 1 or 2 at a time. Return the minimum cost to reach the top.",
    "O(n) time, O(1) space", fn("minCostClimbingStairs(cost: number[]): number")),
  p("house-robber", "House Robber", "Medium", "1-D Dynamic Programming",
    "Return the most money you can rob from a row of houses without taking from two adjacent ones.",
    "O(n) time, O(1) space", fn("rob(nums: number[]): number")),
  p("house-robber-ii", "House Robber II", "Medium", "1-D Dynamic Programming",
    "Same as House Robber, but the houses are arranged in a circle so the first and last are adjacent.",
    "O(n) time, O(1) space", fn("rob(nums: number[]): number")),
  p("longest-palindromic-substring", "Longest Palindromic Substring", "Medium", "1-D Dynamic Programming",
    "Return the longest contiguous substring of s that is a palindrome.",
    "O(n^2) time", fn("longestPalindrome(s: string): string")),
  p("palindromic-substrings", "Palindromic Substrings", "Medium", "1-D Dynamic Programming",
    "Count how many contiguous substrings of s are palindromes.",
    "O(n^2) time", fn("countSubstrings(s: string): number")),
  p("decode-ways", "Decode Ways", "Medium", "1-D Dynamic Programming",
    "Digits map to letters as 1→A … 26→Z; return how many ways a digit string can be decoded.",
    "O(n) time", fn("numDecodings(s: string): number")),
  p("coin-change", "Coin Change", "Medium", "1-D Dynamic Programming",
    "Given coin denominations and an amount, return the fewest coins that make the amount, or -1 if impossible.",
    "O(amount·coins) time", fn("coinChange(coins: number[], amount: number): number")),
  p("max-product-subarray", "Maximum Product Subarray", "Medium", "1-D Dynamic Programming",
    "Return the largest product of any contiguous subarray (at least one element).",
    "O(n) time", fn("maxProduct(nums: number[]): number")),
  p("word-break", "Word Break", "Medium", "1-D Dynamic Programming",
    "Return true if s can be segmented into a space-separated sequence of words from the given dictionary.",
    "O(n^2) time", fn("wordBreak(s: string, wordDict: string[]): boolean")),
  p("longest-increasing-subsequence", "Longest Increasing Subsequence", "Medium", "1-D Dynamic Programming",
    "Return the length of the longest strictly increasing subsequence (not necessarily contiguous).",
    "O(n log n) time", fn("lengthOfLIS(nums: number[]): number")),
  p("partition-equal-subset", "Partition Equal Subset Sum", "Medium", "1-D Dynamic Programming",
    "Return true if the array can be split into two subsets with equal sums.",
    "O(n·sum) time", fn("canPartition(nums: number[]): boolean")),

  // ---------- 2-D Dynamic Programming ----------
  p("unique-paths", "Unique Paths", "Medium", "2-D Dynamic Programming",
    "Count the distinct paths a robot can take from the top-left to bottom-right of an m×n grid moving only right or down.",
    "O(m·n) time", fn("uniquePaths(m: number, n: number): number")),
  p("longest-common-subsequence", "Longest Common Subsequence", "Medium", "2-D Dynamic Programming",
    "Return the length of the longest subsequence common to two strings.",
    "O(m·n) time", fn("longestCommonSubsequence(a: string, b: string): number")),
  p("buy-sell-cooldown", "Best Time to Buy/Sell Stock With Cooldown", "Medium", "2-D Dynamic Programming",
    "Maximize profit from unlimited transactions where you must wait one day after selling before buying again.",
    "O(n) time", fn("maxProfit(prices: number[]): number")),
  p("coin-change-ii", "Coin Change II", "Medium", "2-D Dynamic Programming",
    "Given coin denominations and an amount, return the number of distinct combinations that make the amount.",
    "O(amount·coins) time", fn("change(amount: number, coins: number[]): number")),
  p("target-sum", "Target Sum", "Medium", "2-D Dynamic Programming",
    "Assign + or − to each number; return how many assignments make the expression equal a target.",
    "O(n·sum) time", fn("findTargetSumWays(nums: number[], target: number): number")),
  p("interleaving-string", "Interleaving String", "Medium", "2-D Dynamic Programming",
    "Return true if s3 can be formed by interleaving s1 and s2 while preserving each one's character order.",
    "O(m·n) time", fn("isInterleave(s1: string, s2: string, s3: string): boolean")),
  p("longest-increasing-path", "Longest Increasing Path in a Matrix", "Hard", "2-D Dynamic Programming",
    "Return the length of the longest strictly increasing path in a grid, moving between adjacent cells.",
    "O(m·n) time", fn("longestIncreasingPath(matrix: number[][]): number")),
  p("distinct-subsequences", "Distinct Subsequences", "Hard", "2-D Dynamic Programming",
    "Return how many distinct subsequences of s equal t.",
    "O(m·n) time", fn("numDistinct(s: string, t: string): number")),
  p("edit-distance", "Edit Distance", "Medium", "2-D Dynamic Programming",
    "Return the minimum number of insertions, deletions, or replacements to turn one word into another.",
    "O(m·n) time", fn("minDistance(word1: string, word2: string): number")),
  p("burst-balloons", "Burst Balloons", "Hard", "2-D Dynamic Programming",
    "Bursting balloon i earns nums[left]·nums[i]·nums[right]; return the maximum coins from bursting all balloons.",
    "O(n^3) time", fn("maxCoins(nums: number[]): number")),
  p("regex-matching", "Regular Expression Matching", "Hard", "2-D Dynamic Programming",
    "Implement matching for '.' (any char) and '*' (zero or more of the previous element) over the entire input.",
    "O(m·n) time", fn("isMatch(s: string, p: string): boolean")),

  // ---------- Greedy ----------
  p("max-subarray", "Maximum Subarray", "Medium", "Greedy",
    "Return the largest sum of any contiguous subarray (at least one element).",
    "O(n) time (Kadane's)", fn("maxSubArray(nums: number[]): number")),
  p("jump-game", "Jump Game", "Medium", "Greedy",
    "Each value is a max jump length; starting at index 0, return whether you can reach the last index.",
    "O(n) time", fn("canJump(nums: number[]): boolean")),
  p("jump-game-ii", "Jump Game II", "Medium", "Greedy",
    "Each value is a max jump length; return the minimum number of jumps to reach the last index.",
    "O(n) time", fn("jump(nums: number[]): number")),
  p("gas-station", "Gas Station", "Medium", "Greedy",
    "Given gas and cost at each station on a circular route, return the start index to complete the loop, or -1.",
    "O(n) time", fn("canCompleteCircuit(gas: number[], cost: number[]): number")),
  p("hand-of-straights", "Hand of Straights", "Medium", "Greedy",
    "Return true if the hand can be rearranged into groups of groupSize consecutive cards.",
    "O(n log n) time", fn("isNStraightHand(hand: number[], groupSize: number): boolean")),
  p("merge-triplets", "Merge Triplets to Form Target", "Medium", "Greedy",
    "Using element-wise max merges on selected triplets, return whether the target triplet can be formed.",
    "O(n) time", fn("mergeTriplets(triplets: number[][], target: number[]): boolean")),
  p("partition-labels", "Partition Labels", "Medium", "Greedy",
    "Split the string into as many pieces as possible so each letter appears in at most one piece; return the piece sizes.",
    "O(n) time", fn("partitionLabels(s: string): number[]")),
  p("valid-parenthesis-string", "Valid Parenthesis String", "Medium", "Greedy",
    "A string of '(', ')', and '*' (which may be '(' , ')' or empty); return whether it can be made a valid parenthesization.",
    "O(n) time", fn("checkValidString(s: string): boolean")),

  // ---------- Intervals ----------
  p("insert-interval", "Insert Interval", "Medium", "Intervals",
    "Given sorted non-overlapping intervals and a new one, insert it and merge as needed, returning the result still sorted.",
    "O(n) time", fn("insert(intervals: number[][], newInterval: number[]): number[][]")),
  p("merge-intervals", "Merge Intervals", "Medium", "Intervals",
    "Merge every set of overlapping intervals and return the non-overlapping result.",
    "O(n log n) time", fn("merge(intervals: number[][]): number[][]")),
  p("non-overlapping-intervals", "Non-overlapping Intervals", "Medium", "Intervals",
    "Return the minimum number of intervals to remove so the rest no longer overlap.",
    "O(n log n) time", fn("eraseOverlapIntervals(intervals: number[][]): number")),
  p("meeting-rooms", "Meeting Rooms", "Easy", "Intervals",
    "Given meeting time intervals, return whether a single person could attend all of them without overlap.",
    "O(n log n) time", fn("canAttendMeetings(intervals: number[][]): boolean")),
  p("meeting-rooms-ii", "Meeting Rooms II", "Medium", "Intervals",
    "Given meeting time intervals, return the minimum number of rooms required to hold all meetings.",
    "O(n log n) time", fn("minMeetingRooms(intervals: number[][]): number")),
  p("min-interval-query", "Minimum Interval to Include Each Query", "Hard", "Intervals",
    "For each query value, return the size of the smallest interval that contains it, or -1 if none does.",
    "O((n+q) log) time", fn("minInterval(intervals: number[][], queries: number[]): number[]")),

  // ---------- Math & Geometry ----------
  p("rotate-image", "Rotate Image", "Medium", "Math & Geometry",
    "Rotate an n×n matrix 90 degrees clockwise in place.",
    "O(n^2) time, O(1) space", fn("rotate(matrix: number[][]): void")),
  p("spiral-matrix", "Spiral Matrix", "Medium", "Math & Geometry",
    "Return all elements of an m×n matrix in spiral order, starting at the top-left going clockwise.",
    "O(m·n) time", fn("spiralOrder(matrix: number[][]): number[]")),
  p("set-matrix-zeroes", "Set Matrix Zeroes", "Medium", "Math & Geometry",
    "If a cell is 0, set its entire row and column to 0, in place, ideally with O(1) extra space.",
    "O(m·n) time, O(1) space", fn("setZeroes(matrix: number[][]): void")),
  p("happy-number", "Happy Number", "Easy", "Math & Geometry",
    "Repeatedly replace a number with the sum of the squares of its digits; return whether this reaches 1.",
    "O(log n) per step", fn("isHappy(n: number): boolean")),
  p("plus-one", "Plus One", "Easy", "Math & Geometry",
    "Given a number as an array of digits (most significant first), add one and return the resulting digits.",
    "O(n) time", fn("plusOne(digits: number[]): number[]")),
  p("pow-x-n", "Pow(x, n)", "Medium", "Math & Geometry",
    "Compute x raised to the integer power n (n may be negative), in logarithmic time.",
    "O(log n) time", fn("myPow(x: number, n: number): number")),
  p("multiply-strings", "Multiply Strings", "Medium", "Math & Geometry",
    "Multiply two non-negative integers given as strings and return the product as a string, without using bigint.",
    "O(m·n) time", fn("multiply(num1: string, num2: string): string")),
  p("detect-squares", "Detect Squares", "Medium", "Math & Geometry",
    "Design a structure that adds points and counts axis-aligned squares formable with a query point as one corner.",
    "O(n) per count",
    `class CountSquares {\n  constructor() {\n\n  }\n  add(point: number[]): void {\n\n  }\n  count(point: number[]): number {\n\n  }\n}`),

  // ---------- Bit Manipulation ----------
  p("single-number", "Single Number", "Easy", "Bit Manipulation",
    "Every element appears twice except one; find the lone element using constant extra space.",
    "O(n) time, O(1) space (XOR)", fn("singleNumber(nums: number[]): number")),
  p("number-of-one-bits", "Number of 1 Bits", "Easy", "Bit Manipulation",
    "Return how many bits are set to 1 in the binary form of an unsigned 32-bit integer.",
    "O(1) time", fn("hammingWeight(n: number): number")),
  p("counting-bits", "Counting Bits", "Easy", "Bit Manipulation",
    "Return an array where position i holds the number of set bits in i, for 0..n.",
    "O(n) time", fn("countBits(n: number): number[]")),
  p("reverse-bits", "Reverse Bits", "Easy", "Bit Manipulation",
    "Reverse the bits of a 32-bit unsigned integer and return the result.",
    "O(1) time", fn("reverseBits(n: number): number")),
  p("missing-number", "Missing Number", "Easy", "Bit Manipulation",
    "An array holds n distinct values from the range [0, n] with one missing; return the missing value.",
    "O(n) time, O(1) space", fn("missingNumber(nums: number[]): number")),
  p("sum-two-integers", "Sum of Two Integers", "Medium", "Bit Manipulation",
    "Return the sum of two integers without using + or -.",
    "O(1) time", fn("getSum(a: number, b: number): number")),
  p("reverse-integer", "Reverse Integer", "Medium", "Bit Manipulation",
    "Reverse the digits of a signed 32-bit integer; return 0 if the result overflows 32 bits.",
    "O(log n) time", fn("reverse(x: number): number")),
];

/** Opt-in pool from the open APPS dataset (built by scripts/build-problems.mjs). */
export const OPEN_PROBLEMS: Problem[] = (
  openProblemsRaw as unknown as Problem[]
).map((prob) => ({
  ...prob,
  constraints: prob.constraints?.length
    ? prob.constraints
    : DEFAULT_INTERVIEW_CONSTRAINTS,
  examples: prob.examples ?? [],
}));

export const OPEN_CATEGORY = "Open Dataset (APPS · interview)";

/** Groups problems by category in display order (curated first, open last). */
export function groupByCategory(problems: Problem[]): [string, Problem[]][] {
  const order = [...CATEGORIES, OPEN_CATEGORY];
  const groups = new Map<string, Problem[]>();
  for (const prob of problems) {
    const list = groups.get(prob.category);
    if (list) list.push(prob);
    else groups.set(prob.category, [prob]);
  }
  return order
    .filter((c) => groups.has(c))
    .map((c) => [c, groups.get(c)!] as [string, Problem[]]);
}
